name: congruency
favicon: null
layout_spectrum: 0.90328
typography_spectrum: 0.42878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005baa'
    - '#000000'
    - '#0000ff'
    - '#b7b8e0'
    - '#00ffff'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.10712047177366912
  rhythmicContrast: 0.38023990113288164
purpose: []
